### ISSUE TITLE
SVN repositories are mistaken for Git on French locale

### ISSUE THREAD

**Issue by fstirlitz** [Autorevision/autorevision#21]
You can guess why.
```
$ svn info 
Chemin : .
Chemin racine de la copie de travail : [DONNÉES EFFACÉES]
URL : svn://svn.code.sf.net/p/libmspack/code
Relative URL: ^/
Racine du dépôt : svn://svn.code.sf.net/p/libmspack/code
UUID du dépôt : 18a31f5d-9092-44d1-ac33-008f6764bcc6
Révision : 220
Type de nœud : répertoire
Tâche programmée : normale
Auteur de la dernière modification : kyz
Révision de la dernière modification : 220
Date de la dernière modification: 2015-02-26 12:18:55 +0100 (jeu 26 fév 2015)
```

Should have probably used `--xml` here…

**Comment by dak180** [comment]
@fstirlitz did this fix your issue?

**Comment by fstirlitz** [comment]
It does, thanks.

**Comment by dak180** [comment]
@fstirlitz glad to hear it; I was not sure because detection of the existence of of an svn repo only requires that `svn info` return something other than an error.

On the other hand, a fair number of the other things that get done with the output later definitely benefit from the `--xml` output.
