### ISSUE TITLE
PHP shouldn't write global variables

### ISSUE THREAD

**Issue by allevo** [Autorevision/autorevision#25]
Hi,
   I have seen, in some languages, the variables are declared in public scope.
For example PHP autorevision writes into $GLOBALS array overwriting any pre-declared global variables.
Like c++ (in hpp), the variable should be declared in a namespace. This pattern saves us from the redeclaration.

For the compatibility for the old version (PHP < 5.3.0), in PHP you can return an array. For example
```
<?php

return array(
     'VCS_TYPE' => 'git',
    ....
);
```

It can be imported using
```
<?php

$autorevision = require 'autorevision.php';

```

Other languages support natively the namespace. If namespace is not supported, you can use a class declaration like java does.
If namespaces or classes are not supported like c, the better choice is to use the global constant definition (#define) because the inclusion fails at "compile time" without any side effect as already does.

NB: PHP before 4.0.0 doesn't support class. So the best way to isolate the constants is to return as array.

**Comment by dak180** [comment]
@allevo Sounds like you have a good idea of how the php output should work for maxim compatibility; feel free to put together a pull request addressing the issues you have brought up.

**Comment by allevo** [comment]
See https://github.com/Autorevision/autorevision/pull/26
