### ISSUE TITLE
Saving formatted to file (for Windows) instead of stdout

### ISSUE THREAD

**Issue by ykil** [Autorevision/autorevision#33]
Hi there. Great work!

I'm trying to make automated system in Windows, using batch and sh.exe installed with git.  But the following does not work as the redirect is already in use:

```
PATH=%PATH%;C:\Program Files (x86)\Git\bin;C:\Program Files\Git\bin
sh.exe autorevision.sh -t hpp > .\git_version.h
line 944: /dev/stdout: Device or resource busy
```

Line 944 refers to this line:
`cat > "${TARGETFILE}" << EOF
`

The question is:
1. Got any idea on solving this redirect issue?
2. Better, if there's a way to write these formatted styles to file, as you do with the cache file.

Thank you very much in advance.

**Comment by ykil** [comment]
ping?

**Comment by chungy** [comment]
can you try the version I posted as PR #34?

**Comment by ykil** [comment]
beautiful! thank you very much.

**Comment by dak180** [comment]
Does 7f7aca7b2029f6f1f32ea73d23b5994d4edd8473 fix your problem?

**Comment by dak180** [comment]
I will close this as presumed to be fixed.
