### ISSUE TITLE
VCS_BASENAME in a git worktree should reflect basename of the main working tree

### ISSUE THREAD

**Issue by kamalmarhubi** [Autorevision/autorevision#38]
### What you are doing?
Using autorevision in conjunction with multiple [git worktrees](https://git-scm.com/docs/git-worktree).

```shell
/tmp$ mkdir repro
/tmp$ cd repro
/tmp/repro$ git init
Initialized empty Git repository in /private/tmp/repro/.git/
/tmp/repro$ git commit --allow-empty --message='Empty commit'
[master (root-commit) a665d16] Empty commit
/tmp/repro$ autorevision.sh -s VCS_BASENAME
repro
/tmp/repro$ git worktree add ../repro-new-worktree
Preparing ../repro-new-worktree (identifier repro-new-worktree)
HEAD is now at a665d16 Empty commit
/tmp/repro$ cd ../repro-new-worktree/
/tmp/repro-new-worktree$ autorevision.sh -s VCS_BASENAME
repro-new-worktree
```

### What do you expect to happen?
I wanted the last output to be `repro`, the basename of the main working tree. Worktrees are used to organize local work. The main working tree's basename is more reflective of the intent of `VCS_BASENAME`.

### What is actually happening?
I got `repro-new-worktree`, the basename of the current worktree.

### What version is Autorevision?
1.19

**Comment by dak180** [comment]
Having thought about this I do not think that this is a good idea; the `VCS_BASENAME` is not meant to be a unique repository identifier, `VCS_UUID` is meant to fill that roll.

**Comment by kamalmarhubi** [comment]
Fair enough.

My reasoning was that the worktree is semantically a branch. The workflows `git stash && git checkout -b quick-fix` and `git worktree add ../quick-fix && cs ../quick-fix` are equivalent from a repo state point of view. It's not to use it as a unique id, but to have the same output regardless of a developer's git usage style.

I guess I can just be sure to visit the main worktree before any builds, or maintain my own version.
