### ISSUE TITLE
Feature request: write to file instead of stdout

### ISSUE THREAD

**Issue by bjornfor** [Autorevision/autorevision#45]
Hi,

I think autorevision would be easier to use in build systems (I'm targeting cmake at the moment) if it knew how to write to a file, and only write when there is a change in the VCS.

Any thoughts on the interface? New option, "-O outputfile"?

**Comment by dak180** [comment]
It actually already does this for the cache file, which is why the [make examples](https://autorevision.github.io/blog/2015/03/15/Examples) use one command near the beginning to unconditionally run to generate the cache file (and get a version string to use in the rest of the file) while the rest of the calls force the use of the cache file and only run when the file cache file changes.

**Comment by dak180** [comment]
On the second part I am not sure I understand; what sort of hoops are we talking about exactly?  Is there some reason why the cache file cannot be the source file for these commands?

For the first part [this stackoverflow question](https://stackoverflow.com/questions/31582344/how-to-redirect-the-output-of-a-cmake-custom-command-to-a-file) seems to indicate a way to do platform independent redirection in cmake or is there something I am missing?  (I freely admit to knowing rather little about cmake and how it works.)

**Comment by bjornfor** [comment]
The hoops are (from memory) needing to use both add_custom_command and add_custom_target. (When testing I ended up with more add_custom_* stuff, but I don't remember all the details.) With the change I'm proposing, only add_custom_target is needed.

I'm not fluent in cmake. But this change, if implemented, at least will make it easier for me.

Using the cache file as dependency does not work, it's the generated header file that the build depends on (C/C++). And currently, in the cmake world, the simplest autorevision implementation results in needless rebuilds as the generated header file (C/C++) gets updated on each run.

Hm, perhaps cmd.exe supports ">" redirection? I always thought it didn't. That eliminates one concern.

Anyway, there is already file + caching support for the "cache file", why not support file + cache for the other outputs?

**Comment by dak180** [comment]
The way I have set things up in every other build systems is as a three step process: step one is to unconditionally run a command that will generate the cache file (which is only updated if it changes), step two is to run the command that generates your desired output format conditional upon a change to the cache file, and step three is to use that output file in the final compilation.

Usually only the first of those requires any special treatment, is that what you were doing?

**Comment by bjornfor** [comment]
I guess I'm looking for a one step process. Hence why this is (was) a feature request.
