### ISSUE TITLE
Ignore untracked files

### ISSUE THREAD

**Issue by soliton-** [Autorevision/autorevision#50]
### What you are doing?
Using autorevision with VCS_WC_MODIFIED.

### What do you expect to happen?
Untracked files get ignored.

### What is actually happening?
Untracked files are not ignored.

This was changed in #13. As an option you can turn off this might make sense even if IMO it's still a weird default.

A meaningful modification is done to tracked files. If the existence of untracked files and whether or not they're ignored (something you can change in git for example without checking anything in) changes how a build behaves then the build system seems pretty broken and the modified flag meaningless anyway.

**Comment by dak180** [comment]
This cannot be done for all supported vcs and is counter to the intended purpose. The only reason that this is an option for SVN is it is a centralized version control system, and requires network access to perform such operations. This has been observed to lead to 20 minute or more delays in running this step even in relatively uncomplicated repositories.

Setting files as ignored (however this is accomplished in the individual VCS) indicates a deliberate acknowledgment by a developer that such files should have no impact on the build process.

**Comment by soliton-** [comment]
> This cannot be done for all supported vcs and is counter to the intended purpose.

Since this was how it worked before #13 it is clearly trivial to have it work that way again. In case it seemed like I'm asking for an option I wasn't. I simply mentioned that an option (even if weird and I don't think it's needed) would be ok.

> Setting files as ignored (however this is accomplished in the individual VCS) indicates a deliberate acknowledgment by a developer that such files should have no impact on the build process.

Sure, no complaints about disregarding ignored file. This issue is about assigning meaning to untracked files that are not ignored.
